from django import forms

class Add(forms.Form):
    latitude = forms.FloatField()
    longitude = forms.FloatField()
    unique_squirrel_id = forms.CharField(max_length=100)
    shift = forms.CharField(max_length=20)
    date = forms.DateField()
    age = forms.CharField(max_length=20)
    primary_fur_color = forms.CharField(max_length=200)
    location  = forms.CharField(max_length=200)
    specific_location  = forms.CharField(max_length=200)
    running = forms.BooleanField(required=False,initial=False)
    chasing = forms.BooleanField(required=False,initial=False)
    climbing = forms.BooleanField(required=False,initial=False)
    eating = forms.BooleanField(required=False,initial=False)
    foraging = forms.BooleanField(required=False,initial=False)
    other_activities = forms.CharField(max_length=200)
    kuks = forms.BooleanField(required=False,initial=False)
    quaas = forms.BooleanField(required=False,initial=False)
    moans = forms.BooleanField(required=False,initial=False)
    tail_flags = forms.BooleanField(required=False,initial=False)
    tail_twitches = forms.BooleanField(required=False,initial=False)
    approaches = forms.BooleanField(required=False,initial=False)
    indifferent = forms.BooleanField(required=False,initial=False)
    runs_from = forms.BooleanField(required=False,initial=False)

