# Generated by Django 2.2.7 on 2019-11-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.FloatField(help_text='Latitude')),
                ('Y', models.FloatField(help_text='Longitude')),
                ('Unique_Squirrel_ID', models.CharField(help_text='Unique Squirrel id', max_length=50)),
                ('Shift', models.CharField(help_text='Shift', max_length=100)),
                ('Date', models.DateField(help_text='Date')),
                ('Hectare_Squirrel_Number', models.IntegerField(help_text='Hectare Squirrel Number')),
                ('Age', models.CharField(help_text='Age category', max_length=100)),
                ('Highlight_Fur_Color', models.CharField(max_length=200)),
                ('Combination_of_Primary_and_Highlight_Color', models.CharField(max_length=200)),
                ('Color_notes', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('Above_Ground_Sighter_Measurement', models.CharField(max_length=200)),
                ('Specific_Location', models.CharField(max_length=200)),
                ('Running', models.BooleanField()),
                ('Chasing', models.BooleanField()),
                ('Climbing', models.BooleanField()),
                ('Eating', models.BooleanField()),
                ('Foraging', models.BooleanField()),
                ('Other', models.CharField(max_length=200)),
                ('Kuks', models.BooleanField()),
                ('Quaas', models.BooleanField()),
                ('Moans', models.BooleanField()),
                ('Tail_flags', models.BooleanField()),
                ('Tail_twitches', models.BooleanField()),
                ('Approaches', models.BooleanField()),
                ('Indifferent', models.BooleanField()),
                ('Runs_from', models.BooleanField()),
                ('Other_Interactions', models.CharField(max_length=200)),
                ('LatLong', models.CharField(max_length=200)),
            ],
        ),
    ]
