# Generated by Django 2.2.7 on 2019-11-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='X',
            new_name='Latitude',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Y',
            new_name='Longitude',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Above_Ground_Sighter_Measurement',
            new_name='Other_Activities',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Color_notes',
            new_name='Primary_Fur_Color',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Combination_of_Primary_and_Highlight_Color',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Hectare_Squirrel_Number',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Highlight_Fur_Color',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='LatLong',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Other',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Other_Interactions',
        ),
    ]
